var posters = [
    {
      "Appreciation" : 2568.68,
      "YEAR" : 1975,
      "NUNSIGNED" : 1300,
      "NSIGNED" : 0,
      "PSIZE" : 432,
      "AFREQUENCY" : 1,
      "ALIFE" : "Alive",
      "MRACE" : "UNKNOWN",
      "MINST_OLD" : "None",
      "MFAME" : 1,
      "MLIFE" : "Alive",
      "MINST" : ""
    },
    {
      "Appreciation" : 1142.75,
      "YEAR" : 1976,
      "NUNSIGNED" : 1000,
      "NSIGNED" : 1000,
      "PSIZE" : 805,
      "AFREQUENCY" : 1,
      "ALIFE" : "Alive",
      "MRACE" : "Black",
      "MINST_OLD" : "None",
      "MFAME" : 1,
      "MLIFE" : "Dead",
      "MINST" : ""
    },
    {
      "Appreciation" : 638.22,
      "YEAR" : 1977,
      "NUNSIGNED" : 5000,
      "NSIGNED" : 500,
      "PSIZE" : 690,
      "AFREQUENCY" : 1,
      "ALIFE" : "Alive",
      "MRACE" : "Black",
      "MINST_OLD" : "Band",
      "MFAME" : 1,
      "MLIFE" : "Alive",
      "MINST" : "O"
    },
    {
      "Appreciation" : 567.23,
      "YEAR" : 1978,
      "NUNSIGNED" : 5000,
      "NSIGNED" : 1000,
      "PSIZE" : 793.5,
      "AFREQUENCY" : 1,
      "ALIFE" : "Alive",
      "MRACE" : "Black",
      "MINST_OLD" : "Band",
      "MFAME" : 1,
      "MLIFE" : "Alive",
      "MINST" : "O"
    },
    {
      "Appreciation" : 388.13,
      "YEAR" : 1979,
      "NUNSIGNED" : 10000,
      "NSIGNED" : 1000,
      "PSIZE" : 969,
      "AFREQUENCY" : 1,
      "ALIFE" : "Alive",
      "MRACE" : "Black",
      "MINST_OLD" : "Woodwind",
      "MFAME" : 1,
      "MLIFE" : "Alive",
      "MINST" : "O"
    },
    {
      "Appreciation" : 480.4,
      "YEAR" : 1980,
      "NUNSIGNED" : 10000,
      "NSIGNED" : 1500,
      "PSIZE" : 737,
      "AFREQUENCY" : 1,
      "ALIFE" : "Alive",
      "MRACE" : "UNKNOWN",
      "MINST_OLD" : "Woodwind",
      "MFAME" : 1,
      "MLIFE" : "Alive",
      "MINST" : "O"
    },
    {
      "Appreciation" : 331.91,
      "YEAR" : 1981,
      "NUNSIGNED" : 12500,
      "NSIGNED" : 2000,
      "PSIZE" : 558,
      "AFREQUENCY" : 1,
      "ALIFE" : "Alive",
      "MRACE" : "UNKNOWN",
      "MINST_OLD" : "Percussion",
      "MFAME" : 1,
      "MLIFE" : "Alive",
      "MINST" : "O"
    },
    {
      "Appreciation" : 275.57,
      "YEAR" : 1982,
      "NUNSIGNED" : 12500,
      "NSIGNED" : 2000,
      "PSIZE" : 672,
      "AFREQUENCY" : 1,
      "ALIFE" : "Alive",
      "MRACE" : "Black",
      "MINST_OLD" : "Band",
      "MFAME" : 1,
      "MLIFE" : "Alive",
      "MINST" : "O"
    },
    {
      "Appreciation" : 166.42,
      "YEAR" : 1983,
      "NUNSIGNED" : 12500,
      "NSIGNED" : 2500,
      "PSIZE" : 600,
      "AFREQUENCY" : 2,
      "ALIFE" : "Dead",
      "MRACE" : "Black",
      "MINST_OLD" : "Percussion",
      "MFAME" : 1,
      "MLIFE" : "Alive",
      "MINST" : "O"
    },
    {
      "Appreciation" : 139.8,
      "YEAR" : 1984,
      "NUNSIGNED" : 12500,
      "NSIGNED" : 2500,
      "PSIZE" : 600,
      "AFREQUENCY" : 1,
      "ALIFE" : "Alive",
      "MRACE" : "Black",
      "MINST_OLD" : "Woodwind",
      "MFAME" : 1,
      "MLIFE" : "Alive",
      "MINST" : "O"
    },
    {
      "Appreciation" : 286.04,
      "YEAR" : 1985,
      "NUNSIGNED" : 12500,
      "NSIGNED" : 2500,
      "PSIZE" : 648,
      "AFREQUENCY" : 1,
      "ALIFE" : "Alive",
      "MRACE" : "Black",
      "MINST_OLD" : "Woodwind",
      "MFAME" : 1,
      "MLIFE" : "Alive",
      "MINST" : "O"
    },
    {
      "Appreciation" : 82.21,
      "YEAR" : 1986,
      "NUNSIGNED" : 12500,
      "NSIGNED" : 2500,
      "PSIZE" : 748,
      "AFREQUENCY" : 1,
      "ALIFE" : "Alive",
      "MRACE" : "UNKNOWN",
      "MINST_OLD" : "Band",
      "MFAME" : 1,
      "MLIFE" : "Alive",
      "MINST" : "O"
    },
    {
      "Appreciation" : 134.42,
      "YEAR" : 1987,
      "NUNSIGNED" : 12500,
      "NSIGNED" : 2500,
      "PSIZE" : 576,
      "AFREQUENCY" : 2,
      "ALIFE" : "Dead",
      "MRACE" : "Black",
      "MINST_OLD" : "Percussion",
      "MFAME" : 1,
      "MLIFE" : "Alive",
      "MINST" : "O"
    },
    {
      "Appreciation" : 101.83,
      "YEAR" : 1988,
      "NUNSIGNED" : 12500,
      "NSIGNED" : 2500,
      "PSIZE" : 640,
      "AFREQUENCY" : 1,
      "ALIFE" : "Alive",
      "MRACE" : "UNKNOWN",
      "MINST_OLD" : "Band",
      "MFAME" : 1,
      "MLIFE" : "Alive",
      "MINST" : "O"
    },
    {
      "Appreciation" : 434.5,
      "YEAR" : 1989,
      "NUNSIGNED" : 12500,
      "NSIGNED" : 2500,
      "PSIZE" : 704,
      "AFREQUENCY" : 1,
      "ALIFE" : "Alive",
      "MRACE" : "Black",
      "MINST_OLD" : "Percussion",
      "MFAME" : 5,
      "MLIFE" : "Alive",
      "MINST" : "O"
    },
    {
      "Appreciation" : 72.35,
      "YEAR" : 1990,
      "NUNSIGNED" : 12500,
      "NSIGNED" : 2500,
      "PSIZE" : 660,
      "AFREQUENCY" : 1,
      "ALIFE" : "Alive",
      "MRACE" : "Black",
      "MINST_OLD" : "Woodwind",
      "MFAME" : 2,
      "MLIFE" : "Dead",
      "MINST" : "O"
    },
    {
      "Appreciation" : 51.5,
      "YEAR" : 1993,
      "NUNSIGNED" : 15000,
      "NSIGNED" : 15000,
      "PSIZE" : 748,
      "AFREQUENCY" : 1,
      "ALIFE" : "Dead",
      "MRACE" : "UNKNOWN",
      "MINST_OLD" : "Band",
      "MFAME" : 1,
      "MLIFE" : "Alive",
      "MINST" : "O"
    },
    {
      "Appreciation" : 108.91,
      "YEAR" : 1994,
      "NUNSIGNED" : 10000,
      "NSIGNED" : 2000,
      "PSIZE" : 432,
      "AFREQUENCY" : 1,
      "ALIFE" : "Alive",
      "MRACE" : "UNKNOWN",
      "MINST_OLD" : "Band",
      "MFAME" : 3,
      "MLIFE" : "Alive",
      "MINST" : "O"
    },
    {
      "Appreciation" : 817.27,
      "YEAR" : 1995,
      "NUNSIGNED" : 10000,
      "NSIGNED" : 2500,
      "PSIZE" : 735,
      "AFREQUENCY" : 3,
      "ALIFE" : "Alive",
      "MRACE" : "Black",
      "MINST_OLD" : "Woodwind",
      "MFAME" : 5,
      "MLIFE" : "Dead",
      "MINST" : "O"
    },
    {
      "Appreciation" : 453.36,
      "YEAR" : 1996,
      "NUNSIGNED" : 10000,
      "NSIGNED" : 3000,
      "PSIZE" : 735,
      "AFREQUENCY" : 3,
      "ALIFE" : "Alive",
      "MRACE" : "White",
      "MINST_OLD" : "Woodwind",
      "MFAME" : 3,
      "MLIFE" : "Alive",
      "MINST" : "O"
    },
    {
      "Appreciation" : 344.97,
      "YEAR" : 1997,
      "NUNSIGNED" : 10000,
      "NSIGNED" : 3000,
      "PSIZE" : 759,
      "AFREQUENCY" : 2,
      "ALIFE" : "Alive",
      "MRACE" : "Black",
      "MINST_OLD" : "Band",
      "MFAME" : 1,
      "MLIFE" : "Alive",
      "MINST" : "O"
    },
    {
      "Appreciation" : 544.04,
      "YEAR" : 1998,
      "NUNSIGNED" : 10000,
      "NSIGNED" : 3000,
      "PSIZE" : 648,
      "AFREQUENCY" : 5,
      "ALIFE" : "Alive",
      "MRACE" : "White",
      "MINST_OLD" : "Percussion",
      "MFAME" : 4,
      "MLIFE" : "Alive",
      "MINST" : "O"
    },
    {
      "Appreciation" : 232.53,
      "YEAR" : 1999,
      "NUNSIGNED" : 10000,
      "NSIGNED" : 3000,
      "PSIZE" : 680,
      "AFREQUENCY" : 1,
      "ALIFE" : "Alive",
      "MRACE" : "Black",
      "MINST_OLD" : "Percussion",
      "MFAME" : 3,
      "MLIFE" : "Dead",
      "MINST" : "O"
    },
    {
      "Appreciation" : 281.4,
      "YEAR" : 2000,
      "NUNSIGNED" : 10000,
      "NSIGNED" : 3000,
      "PSIZE" : 735,
      "AFREQUENCY" : 3,
      "ALIFE" : "Alive",
      "MRACE" : "White",
      "MINST_OLD" : "Woodwind",
      "MFAME" : 3,
      "MLIFE" : "Dead",
      "MINST" : "O"
    },
    {
      "Appreciation" : 563.58,
      "YEAR" : 2001,
      "NUNSIGNED" : 10000,
      "NSIGNED" : 3000,
      "PSIZE" : 828,
      "AFREQUENCY" : 5,
      "ALIFE" : "Alive",
      "MRACE" : "Black",
      "MINST_OLD" : "Woodwind",
      "MFAME" : 5,
      "MLIFE" : "Dead",
      "MINST" : "O"
    },
    {
      "Appreciation" : 174.77,
      "YEAR" : 2002,
      "NUNSIGNED" : 10000,
      "NSIGNED" : 3000,
      "PSIZE" : 665,
      "AFREQUENCY" : 1,
      "ALIFE" : "Alive",
      "MRACE" : "Black",
      "MINST_OLD" : "Woodwind",
      "MFAME" : 4,
      "MLIFE" : "Alive",
      "MINST" : "O"
    },
    {
      "Appreciation" : 87.67,
      "YEAR" : 2003,
      "NUNSIGNED" : 10000,
      "NSIGNED" : 3000,
      "PSIZE" : 684,
      "AFREQUENCY" : 5,
      "ALIFE" : "Alive",
      "MRACE" : "Black",
      "MINST_OLD" : "Voice",
      "MFAME" : 5,
      "MLIFE" : "Dead",
      "MINST" : "V"
    },
    {
      "Appreciation" : 53.35,
      "YEAR" : 2004,
      "NUNSIGNED" : 10000,
      "NSIGNED" : 3000,
      "PSIZE" : 700,
      "AFREQUENCY" : 1,
      "ALIFE" : "Alive",
      "MRACE" : "White",
      "MINST_OLD" : "Percussion",
      "MFAME" : 5,
      "MLIFE" : "Alive",
      "MINST" : "O"
    },
    {
      "Appreciation" : 105.7,
      "YEAR" : 2005,
      "NUNSIGNED" : 10000,
      "NSIGNED" : 3000,
      "PSIZE" : 736,
      "AFREQUENCY" : 1,
      "ALIFE" : "Alive",
      "MRACE" : "Black",
      "MINST_OLD" : "Band",
      "MFAME" : 3,
      "MLIFE" : "Dead",
      "MINST" : "O"
    },
    {
      "Appreciation" : 317.87,
      "YEAR" : 2006,
      "NUNSIGNED" : 12500,
      "NSIGNED" : 3500,
      "PSIZE" : 720,
      "AFREQUENCY" : 5,
      "ALIFE" : "Alive",
      "MRACE" : "Black",
      "MINST_OLD" : "Percussion",
      "MFAME" : 5,
      "MLIFE" : "Alive",
      "MINST" : "O"
    },
    {
      "Appreciation" : 53.66,
      "YEAR" : 2007,
      "NUNSIGNED" : 10000,
      "NSIGNED" : 3000,
      "PSIZE" : 814,
      "AFREQUENCY" : 2,
      "ALIFE" : "Alive",
      "MRACE" : "White",
      "MINST_OLD" : "Percussion",
      "MFAME" : 5,
      "MLIFE" : "Alive",
      "MINST" : "O"
    },
    {
      "Appreciation" : 51.48,
      "YEAR" : 2008,
      "NUNSIGNED" : 10000,
      "NSIGNED" : 3000,
      "PSIZE" : 544,
      "AFREQUENCY" : 1,
      "ALIFE" : "Alive",
      "MRACE" : "Black",
      "MINST_OLD" : "Voice",
      "MFAME" : 4,
      "MLIFE" : "Alive",
      "MINST" : "V"
    },
    {
      "Appreciation" : 56.22,
      "YEAR" : 2009,
      "NUNSIGNED" : 10000,
      "NSIGNED" : 3000,
      "PSIZE" : 720,
      "AFREQUENCY" : 5,
      "ALIFE" : "Alive",
      "MRACE" : "Black",
      "MINST_OLD" : "Percussion",
      "MFAME" : 3,
      "MLIFE" : "Alive",
      "MINST" : "O"
    },
    {
      "Appreciation" : 22.41,
      "YEAR" : 2010,
      "NUNSIGNED" : 12500,
      "NSIGNED" : 2000,
      "PSIZE" : 805,
      "AFREQUENCY" : 1,
      "ALIFE" : "Alive",
      "MRACE" : "White",
      "MINST_OLD" : "Woodwind",
      "MFAME" : 4,
      "MLIFE" : "Alive",
      "MINST" : "O"
    },
    {
      "Appreciation" : -1.44,
      "YEAR" : 2011,
      "NUNSIGNED" : 10000,
      "NSIGNED" : 3000,
      "PSIZE" : 684,
      "AFREQUENCY" : 1,
      "ALIFE" : "Alive",
      "MRACE" : "White",
      "MINST_OLD" : "Voice",
      "MFAME" : 5,
      "MLIFE" : "Alive",
      "MINST" : "V"
    },
    {
      "Appreciation" : 0,
      "YEAR" : 2012,
      "NUNSIGNED" : 10000,
      "NSIGNED" : 2500,
      "PSIZE" : 665,
      "AFREQUENCY" : 1,
      "ALIFE" : "Alive",
      "MRACE" : "Black",
      "MINST_OLD" : "Band",
      "MFAME" : 3,
      "MLIFE" : "Alive",
      "MINST" : "O"
    }
  ];